export * from "./token.command.vk"
export * from "./status.command.vk"
export * from "./stickers.command.vk"
export * from "./dateReg.command"
export * from "./conf.command.vk"
export * from "./intelligenceService.command"
export { getChat } from "./getChat"
